# Generated by Django 6.0.8 on 2026-09-18 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(default='chat_query', max_length=50)),
                ('query_text', models.TextField()),
                ('response_summary', models.TextField()),
                ('source_sections', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(default='gpt-4o', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('escalation_triggered', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
