# Generated by Django 6.0.8 on 2026-09-18 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiauditlog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document'),
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_aiaud_user_id_406642_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['document', 'timestamp'], name='audit_aiaud_documen_4a5999_idx'),
        ),
    ]
