# Generated by Django 6.0.8 on 2026-09-18 13:23

import apps.documents.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1E3A5F', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('employment', 'Employment Contract'), ('rental', 'Rental / Lease Agreement'), ('nda', 'Non-Disclosure Agreement (NDA)'), ('privacy', 'Privacy Policy / Terms of Service'), ('service', 'Master Service Agreement (MSA)'), ('legal_notice', 'Legal Notice / Court Notice'), ('commercial', 'Commercial Contract'), ('general', 'General Legal Document')], default='general', max_length=30)),
                ('file', models.FileField(upload_to=apps.documents.storage.document_upload_path, validators=[apps.documents.storage.validate_uploaded_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('processing', 'Processing & Embedding'), ('ready', 'Ready for Analysis'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status', 'is_deleted'], name='documents_d_owner_i_8d5f88_idx'), models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx')],
            },
        ),
    ]
