# Generated by Django 6.0.8 on 2026-09-18 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending AI Processing'), ('processing', 'Analyzing Document Clauses'), ('complete', 'Analysis Complete'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
                ('explanation_mode', models.CharField(default='beginner', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('clauses_data', models.JSONField(blank=True, default=list)),
                ('risk_metrics', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(default=0, help_text='Composite score 0-100')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Moderate Review Advised'), ('high', 'High Risk'), ('legal_review_advised', 'Professional Legal Review Recommended')], default='low', max_length=30)),
                ('escalation_recommended', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('model_used', models.CharField(default='gpt-4o', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('comparison_data', models.JSONField(default=dict)),
                ('status', models.CharField(default='complete', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
