# Generated by Django 6.0.8 on 2026-09-18 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.document'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='document_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_doc_a', to='documents.document'),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='document_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_doc_b', to='documents.document'),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['document', 'status'], name='analysis_an_documen_96bf14_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['user', 'created_at'], name='analysis_an_user_id_660b45_idx'),
        ),
    ]
